puppeteer/replay

.github/workflows/publish-on-tag.yml

to address the 402 error https://github.com/puppeteer/replay/runs/5286515692?check_suite_focus=true

chore: publish using --access=public

---

src/PuppeteerRunnerExtension.ts
test/runner_test.ts

feature: close select dropdown after the change step

---

docs/api/interfaces/Schema.KeyDownStep.md
docs/api/interfaces/Schema.KeyUpStep.md
docs/api/modules/Schema.md
src/Schema.ts

fix: expose Key to make sure it's included in types

---

README.md

seems to be working as expected after publishing to NPM!

docs: document the CLI

---

src/Schema.ts

docs: fix example step type

---

package.json
rollup.config.ts
src/CLIUtils.ts
src/PuppeteerRunnerExtension.ts
src/cli.ts
src/main.ts
tsconfig.cjs.json
tsconfig.cli.json
tsconfig.json

This PR adds `rollup` as the predominant build system for this repo. In particular, the migration to rollup allows us to bundle types.

feat: bundle types

---

src/Runner.ts
test/runner_test.ts

Adds an `abort` function that stops running the remaining steps.

feat!: add `abort` function to `Runner` and remove `stepIdx` parameter from `run` method

---

docs/api/README.md
docs/api/classes/PuppeteerRunnerOwningBrowserExtension.md
docs/api/classes/Runner.md

Apparently I forgot to commit these while doing the release process

docs: update api docs after `abort` changes

---

.eslintrc.cjs
test/cli.test.ts

Fixes:
https://github.com/puppeteer/replay/blob/369c8238fb1294ab5758bf2945ac0c3c5d07cff5/test/cli.test.ts#L29-L34
Hi @ergunsh!
I solved the problem that you mentioned on your pr. Can you review it?
Reference: https://github.com/typescript-eslint/typescript-eslint/issues/2619#issuecomment-701901752
Have a nice day 🎉

chore: fix eslint `no-unused-vars` error

---

package.json
src/CLIUtils.ts
test/cli.test.ts

Fixes https://github.com/puppeteer/replay/pull/224#issuecomment-1197998889

chore: replace `colors` package with `colorette`

---

package-lock.json
package.json
src/PuppeteerRunnerExtension.ts

BREAKING CHANGE: this version is compatible with Puppeteer >= v16.2.0

feat: update Puppeteer to v16.2.0

---

src/SchemaUtils.ts

fix: using the correct ('navigate') step type within the parseNavigateStep method

---

test/everything.test.ts
test/resources/everything.html
test/resources/everything.json

Note that the current test does not actually test all the features yet. Frames and navigation events are still missing as well as scrolling.
The test makes sure the interpreter and compiled runs result in same observable effects.
Fixes #268

chore: add an "everything" test

---

rollup.config.ts

chore: rollup config - updated list of external modules to exclude

---

rollup.config.cjs
src/main.ts

Closes https://github.com/puppeteer/replay/issues/334

fix: prevent bundling Lighthouse

---

__snapshots__/LighthouseStringifyExtension.test.ts.js
__snapshots__/lighthouse-e2e.test.ts.js
package-lock.json
package.json
src/lighthouse/LighthouseRunnerExtension.ts
src/lighthouse/LighthouseStringifyExtension.ts
test/lighthouse/lighthouse-e2e.test.ts

Lighthouse has had a filesystem reorg since the last dev build we are using.

chore(deps-dev): bump lighthouse to latest dev release

---

docs/api/README.md
docs/api/classes/Runner.md
src/Runner.ts
src/lighthouse/LighthouseRunnerExtension.ts
test/runner.test.ts

This allows for a simpler usage if the user wants to run individual steps.

fix: allow specifying no flow when creating a runner

---

src/main.ts
src/stringify.ts
test/stringify.test.ts

This PR adds a helper for parsing a source map
from a recording.

feat: parse source map

---

examples/chrome-extension-replay/Replay.html

docs: remove header from the sample extension

---

__snapshots__/LighthouseStringifyExtension.test.ts.js
__snapshots__/lighthouse.test.ts.js
package-lock.json
package.json
src/lighthouse/LighthouseRunnerExtension.ts
src/lighthouse/LighthouseStringifyExtension.ts

With the release of Lighthouse 10.0, we can finally upgrade this and add it directly to the replay panel 🎉

chore: upgrade Lighthouse to 10.0.0

---

docs/api/README.md
docs/api/classes/LighthouseRunnerExtension.md
docs/api/classes/PuppeteerRunnerExtension.md

Documentation update to trigger a new release. The implementation has been already there but not released.

feat: Lighthouse extension

---

examples/chrome-extension-replay/README.md

Fixes https://github.com/GoogleChrome/developer.chrome.com/issues/5707.

docs: update README.md

---

package-lock.json
package.json
src/PuppeteerRunnerExtension.ts
src/PuppeteerStringifyExtension.ts
src/Spec.ts

It's known that clickCount doesn't click per count, so we add an additional click with the correct count. We also start handling duration in DoubeClick steps.
This PR also updates Puppeteer to the versions required by this PR.

chore: fix double click

---

.github/workflows/main.yml
.github/workflows/pre-release.yml
.github/workflows/publish.yml
.github/workflows/scorecards-analysis.yml

ci: pin dependencies

---

package-lock.json
package.json
tsconfig.base.json

fix: bumps version for Node and TS target

---

README.md

Fixes minor typo's in `Readme.md`

docs: fixed minor typos

---

.github/workflows/release-please.yml

Closes https://github.com/puppeteer/replay/issues/1024

build: add release-please action
