puppeteer/replay

- package.json
- src/CLIUtils.ts
- src/cli.ts
- test/cli_test.ts
- test/resources/replay.json
This PR implements a basic CLI for running multiple JSON files. It also declares Puppeteer as an optional peer dependency. This PR does not include any public facing documentation yet as I would like to test the workflow once it's published to NPM,  iterate and write documentation.
> feat: implement a CLI to run multiple JSON files

- README.md
- src/CLIUtils.ts
- src/cli.ts
- test/cli_test.ts
The feature is requested in https://github.com/puppeteer/replay/pull/118
> feat: support PUPPETEER_HEADLESS variable

- __snapshots__/stringify_test.ts.js
- src/PuppeteerStringifyExtension.ts
Whenever I've looked at the pptr output I gotta scroll past the 150 lines of boilerplate at the top of the file to get to the actual steps. Since function hoisting is automatic and easy, there's no reason we can't move 'em down to prioritize showing the important stuff.
wdyt?
cc @adamraine
> chore: move helpers to bottom of stringify output

- src/InMemoryLineWriter.ts
- src/stringify.ts
- test/InMemoryLineWriter_test.ts
- test/PuppeteerStringifyExtension_test.ts
This PR allows users to implement their own custom `LineWriter`s. It also renames `LineWriterImpl` to `InMemoryLineWriter`.
> feat: allow custom line writers

- package.json
https://nodejs.org/docs/latest-v12.x/api/packages.html#packages_main
`"main"` is used as the entry point whenever a package is imported via `require` so it should point to the CJS entry point. 
This isn't normally an issue because `"exports"` will override `"main"`. However, Jest doesn't appear to have this behavior, and it will use `"main"` as the default entry point.
Possibly related https://github.com/puppeteer/replay/issues/188
> Make cjs the main package entry point

- README.md
- src/CLIUtils.ts
- src/cli.ts
- test/cli.test.ts
- test/resources/replay-fail.json
> feat: run all recording files in directory with cli

- package.json
- src/CLIUtils.ts
- test/cli.test.ts
> feat: implement status report

- src/SchemaUtils.ts
- src/main.ts
Spreading all SchemaUtils.js exports and using read-only types on exported objects to prevent mutation.
> chore: spreading all SchemaUtils exports

- src/PuppeteerRunnerExtension.ts
- test/resources/invisible-parent.html
- test/runner.test.ts
It's possible that a parent has an invisible bounding box while child elements are perfectly visible. Therefore, we should only apply visible=true for the last selector in the chain.
> fix: check for visibility of the last selected element only

- .github/workflows/main.yml
- .github/workflows/pre-release.yml
- .github/workflows/publish.yml
- .gitignore
- package-lock.json
- package.json
Also replaces `npm install` with `npm ci` in workflows.
> chore: pin dependencies and use package-lock.json

- package-lock.json
- package.json
Hi there!
Attempting to install puppeteer v16 together with this package results in a conflict, see the reproducer below.
Looking at recent PRs (https://github.com/puppeteer/replay/pull/239 / https://github.com/puppeteer/replay/pull/248), this package seems to be compatible with v16, and the missed update of the `peerDependencies` spec was likely an oversight.
This PR is adding the v16 version spec from the `devDependencies` as a secondary version to the `peerDependencies`, which fixes the conflict.
(Let me know if you want a dedicated issue for the bug. The fix seemed too trivial to bother creating an issue for.)
<details>
<summary> reproducer </summary>
package.json:
```json
{
"dependencies": {
"puppeteer": "^16.1.0",
"@puppeteer/replay": "^0.6.1"
}
}
``` 
```bash
$ npm install
npm ERR! …
```
> chore: allow puppeteer v15 and v16 as peerDependency

- __snapshots__/stringify.test.ts.js
- src/PuppeteerStringifyExtension.ts
I noticed there were missing quotes around the click type in the puppeteer stringify extension.
> fix: Puppeteer stringified button click type

- .eslintrc.cjs
We have some unused vars for documentation purposes but
the emitted warnings get picked up by GitHub and shown in
the diff view in pull requests making it impossible to review.
Although we could suppress only those specific warnings, I think
the warning is not that useful anyway so that we can turn all of
them off.
> chore: turn off warn for not used vars

- __snapshots__/lighthouse-e2e.test.ts.js
- __snapshots__/stringify.test.ts.js
- src/PuppeteerRunnerExtension.ts
- src/PuppeteerStringifyExtension.ts
An uncleared timeout results in an open handle that prevents the process from exiting.
Running the tests demonstrates this clearly-
before-
after-
> fix: (waitForFunction) clearing timeout when callback function returns a truthy value

- .github/workflows/scorecards-analysis.yml
See https://github.com/ossf/scorecard-action/issues/900
Example failure with scorecard-action@2 https://github.com/puppeteer/replay/actions/runs/3060651741/jobs/4939423471
> chore: add id-token permissions to scorecard-action

- .mocharc.cjs
- __snapshots__/PuppeteerStringifyExtension.test.ts.js
- __snapshots__/lighthouse-e2e.test.ts.js
- __snapshots__/stringify.test.ts.js
- src/PuppeteerStringifyExtension.ts
- test/cli.test.ts
- test/everything.test.ts
- test/resources/everything.html
- test/resources/everything.json
- test/resources/folder-test/replay-fail.json
- test/resources/folder-test/replay.json
Drive-by: changing dot to spec as the mocha reporter to allow easily seeing which tests are run.
Drive-by: moved the recordings used in cli tests for testing interactions with folders to a dedicated subfolder so that the everything.json test is not run.
Fixes https://crbug.com/1351382
> fix: align typing behaviour between runner and stringifier

- __snapshots__/lighthouse-e2e.test.ts.js
- test/lighthouse/lighthouse-e2e.test.ts
Part of #344 
The final timespan step doesn't add much value to the e2e test runner so I think it's fine to remove. Reduces the length of each e2e test from ~33s to ~26s on my Macbook.
> core(lighthouse): use fewer steps in e2e tests

- src/Runner.ts
- test/runner.test.ts
It's useful if you want to combine these hooks with custom runStep invocations.
> feat: allow the runner to run beforeAll/afterAll hooks

- test/everything.test.ts
- test/resources/everything.expected.txt
This makes it easier for the integrations to consume the test file, the test recording and the expected results.
> docs: move test expectations for the everything test

- src/Schema.ts
- src/SchemaUtils.ts
- test/SchemaUtils.test.ts
Exposes an enum of SelectorTypes we support and
allows getting a type from a string.
> feat: expose getSelectorType

- __snapshots__/PuppeteerReplayStringifyExtension.test.ts.js
- src/InMemoryLineWriter.ts
- src/LineWriter.ts
- src/PuppeteerReplayStringifyExtension.ts
- src/main.ts
- test/PuppeteerReplayStringifyExtension.test.ts
This PR adds a possibility to convert a user flow into a JS script that makes use of the replay's lib own APIs to execute the flow. It adds a method to LineWrite to get the current indent and modifies the appendLine to allow for multiline input that could be formatted better.
> feat: add PuppeteerReplayStringifyExtension

- __snapshots__/PuppeteerReplayStringifyExtension.test.ts.js
- __snapshots__/lighthouse.test.ts.js
- __snapshots__/stringify.test.ts.js
- package-lock.json
- package.json
- src/@types/vlq/index.d.ts
- src/InMemoryLineWriter.ts
- src/LineWriter.ts
- src/stringify.ts
- test/stringify.test.ts
- tsconfig.base.json
This PR adds source map generation for the Recorder. The source map format is custom since we only need to map step idx to lines. Source maps are VLQ encoded.
> feat: generate recorder sourcemaps

- __snapshots__/PuppeteerReplayStringifyExtension.test.ts.js
- __snapshots__/lighthouse.test.ts.js
- __snapshots__/stringify.test.ts.js
- package-lock.json
- package.json
- src/@types/vlq/index.d.ts
- src/stringify.ts
- src/vlq.ts
- test/stringify.test.ts
- test/vlq.test.ts
- tsconfig.base.json
removes the 3rd party libary for vlq.
> fix: change vlq encoding to encode only positive ints

- package.json
- rollup.config.cjs
Fixes #400 
> It's a good idea to open an issue first for discussion.
- [ x ] Tests pass
- [ x ] Appropriate changes to README are included in PR
> fix: support typescript commonjs modules using moduleresolution nodenext 

- __snapshots__/lighthouse.test.ts.js
- __snapshots__/stringify.test.ts.js
- src/PuppeteerRunnerExtension.ts
- src/PuppeteerStringifyExtension.ts
- src/Schema.ts
- src/types.ts
- test/resources/benchmark.json
- test/resources/shadow-dynamic.html
- test/runner.test.ts
This PR adds three new properties:
- `attributes` - This is a dictionary of strings that will match attributes of an element. This will always be a partial match.
For example, `”attributes”: {“value”: “125”}`.
- `properties` - This is a JS record of JSON-serializable attributes that can be used to match an element’s JSON-serializable properties. This will be a sub-tree exact match. For arrays, order matters.
- `visible` - This is a boolean value that inverts the match criteria.
> feat: add `visible`, `properties`, and `attributes` to `waitForElement`

- src/PuppeteerRunnerExtension.ts
- src/SchemaUtils.ts
- test/SchemaUtils.test.ts
- test/resources/benchmark.json
This PR adds parsing to the attributes added in https://github.com/puppeteer/replay/pull/412.
> fix: add parsing for `visible`, `attributes`, and `properties`

- src/main.ts
This was originally removed in https://github.com/puppeteer/replay/pull/337
Now that Lighthouse is a peer dependency we should be able to include it.
> feat: expose Lighthouse runner extension

- package-lock.json
- package.json
The 10.0.1 release removed quibble from package deps so we don't need the override anymore.
> chore: upgrade Lighthouse to 10.0.1

- src/PuppeteerRunnerExtension.ts
- test/runner.test.ts
This PR fixes a bug where an svg owner is null if the target element is an svg element already.
Drive-by: noticed missing dispose calls.
> fix: find the svg owner element

- src/PuppeteerStringifyExtension.ts
- src/Schema.ts
- src/SchemaUtils.ts
All clicks have a duration (even double clicks [it's the last click]) associated with them within Chrome. We should reflect that here.
> feat: move `duration` to click attributes

- package-lock.json
- package.json
- src/PuppeteerRunnerExtension.ts
Note that the Stringify extension can still use Locators as envisioned in the generated code and only the Runner extension needs to avoid the static dependency on Puppeteer.
> fix: access locators via a shortcut

- src/PuppeteerRunnerExtension.ts
Remove deprecated Puppeteer method.
> fix: remove deprecated waitForTimeout

- __snapshots__/LighthouseStringifyExtension.test.ts.js
- src/PuppeteerStringifyExtension.ts
> fix: do not wait for navigation event in navigate steps

- .github/workflows/main.yml
Chrome requires an ability to create sandboxes and by default AppArmor disallows that.
> test: disable apparmor on ubuntu
